"""
Slices a directional walk-cycle sheet into individual frames. "Right" 
isn't stored in the sheet, because it's generated by flipping "left" 
horizontally.
"""

import pygame
import os
from game.assets import ASSETS_DIR

_sheet_cache = {}


class SpriteSheet:
    def __init__(self, surface, frame_size, frames_per_row):
        self.frame_size = frame_size
        self.frames = {"down": [], "up": [], "left": [], "right": []}
        row_order = ["down", "up", "left"]
        for row, direction in enumerate(row_order):
            for col in range(frames_per_row):
                rect = pygame.Rect(col * frame_size, row * frame_size, frame_size, frame_size)
                self.frames[direction].append(surface.subsurface(rect).copy())
        self.frames["right"] = [pygame.transform.flip(f, True, False) for f in self.frames["left"]]

    def get_frames(self, direction):
        return self.frames[direction]


def try_load_spritesheet(relative_path, frame_size=32, frames_per_row=4):
    """relative_path is relative to assets/, e.g. 'zombies/normal/walk.png'."""
    key = (relative_path, frame_size, frames_per_row)
    if key in _sheet_cache:
        return _sheet_cache[key]

    full_path = os.path.join(ASSETS_DIR, relative_path)
    if not os.path.isfile(full_path):
        _sheet_cache[key] = None
        return None

    try:
        surface = pygame.image.load(full_path).convert_alpha()
        sheet = SpriteSheet(surface, frame_size, frames_per_row)
    except (pygame.error, ValueError):
        sheet = None

    _sheet_cache[key] = sheet
    return sheet
